Translate the readme
gatsbyjs/gatsby-id pull request #2
Opened 2019-10-28 22:24 UTC by cendekia

2019-10-28 22:57 UTC, tesseralis commented
@coroo could you review this? and if you're not in the gatsbyjs org yet, could you accept the invitation?

2019-10-29 00:42 UTC, coroo commented on README.md
> +* [Panduan Style](/style-guide.md)
Its better to use: "Panduan Penulisan"

2019-10-29 00:43 UTC, coroo requested changes
Please completed my comment above, thank you

2019-10-29 00:51 UTC, cendekia commented
@coroo 
https://github.com/gatsbyjs/gatsby-id/pull/2/commits/3a47b5529eed8796c4396537fa31a59342e92796

Done :)))

2019-10-29 00:54 UTC, coroo approved these changes

2019-10-29 00:55 UTC, merged