Translate Reference Guides
gatsbyjs/gatsby-id pull request #37
Opened 2019-11-13 18:12 UTC by zweimach

Please review my translation. Thank you.

2019-11-14 01:56 UTC, coroo commented on docs/docs/guides.md
> +Gali lebih dalam tentang topik-topik seputar mengembangkan dengan Gatsby, seperti *sourcing* data, membuat dan menghias laman, *deployment*, dan banyak lagi. Meskipun [tutorial](/tutorial/) adalah pe
Please help to change laman with halaman

2019-11-14 01:57 UTC, coroo requested changes
Thank you, please help us to update some comment abive

2019-11-14 03:12 UTC, zweimach commented
@coroo, thank you for your feedback.

2019-11-16 05:05 UTC, coroo approved these changes
Hi @zweimach , thank you for your help.
Please dont forget to get your swag

2019-11-16 05:05 UTC, merged