Translate Adding a Service Worker
gatsbyjs/gatsby-id pull request #38
Opened 2019-11-13 18:21 UTC by zweimach

Please review my translation. Thank you.

2019-11-14 01:57 UTC, coroo commented on docs/docs/add-a-service-worker.md
> +*Service worker* adalah *script* yang dijalankan oleh peramban web anda di balik layar, terpisah dengan laman web, membuka pintu untuk fitur-fitur yang tidak memerlukan laman web atau interaksi denga
Please help to change laman to halaman

2019-11-14 01:59 UTC, coroo requested changes
Hi, please help us to change some comment above before we merge it

2019-11-14 02:01 UTC, coroo commented
Its ok @zweimach . For this one, I think we need to wait from previous commit first before I can merge yours

2019-11-14 03:16 UTC, zweimach commented
@coroo, thank you for your consideration.

2019-11-16 05:06 UTC, coroo approved these changes

2019-11-16 05:06 UTC, merged