Translate API Files
gatsbyjs/gatsby-id pull request #39
Opened 2019-11-13 19:37 UTC by zweimach

Please review my translation. Thank you.

2019-11-14 01:53 UTC, coroo commented on docs/docs/api-files.md
> +- [gatsby-browser.js](/docs/api-files-gatsby-browser) - Memberikan Anda kendali atas perilaku Gatsby di peramban web. Sebagai contoh, memberikan respon terhadap pengguna yang berpindah rute, atau mem
Can you change laman to halaman? Since laman is the homepage based on this reference: https://kbbi.kemdikbud.go.id/entri/Laman

2019-11-14 01:53 UTC, coroo commented on docs/docs/api-files.md
> +- [gatsby-node.js](/docs/api-files-gatsby-node) - Memungkinkan Anda untuk merespon *event* pada *build cycle* Gatsby. Sebagai contoh, menambahkan laman secara dinamis, mengubah *node* GraphQL saat di
Also laman in this line

2019-11-14 01:53 UTC, coroo commented on docs/docs/api-files.md
> +- [gatsby-ssr.js](/docs/api-files-gatsby-ssr) - Mengekspos proses *server-side rendering* Gatsby sehingga Anda dapat mengendalikan bagaimana Gatsby membangun laman HTML Anda.
Also laman in here

2019-11-14 01:55 UTC, coroo requested changes
Hi @zweimach , thank you for your enthusiasm.
We need help again from you to update some translation as comment, please help before we merge it 😁

2019-11-14 03:07 UTC, zweimach commented
@coroo, thank you for your feedback.

2019-11-16 05:06 UTC, coroo approved these changes

2019-11-16 05:06 UTC, merged