Translate docs/index
gatsbyjs/gatsby-id pull request #4
Opened 2019-10-29 06:28 UTC by bangunbagustapa

Translated docs/index. But there's no index.md file before in docs/docs/ so i have to add the english version first. To compare, please refer to [this commit](https://github.com/gatsbyjs/gatsby-id/commit/88538c4aad2fec11299d3f128df678d4e797a2e0) or [this page](https://www.gatsbyjs.org/docs/).

Please kindly review my work, thanks.

2019-10-29 23:15 UTC, cendekia requested changes

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +2. [Mulai cepat](/docs/quick-start): Ringkasan dalam satu halaman tentang cara menginstal Gatsby dan memulai proyek baru.
Lebih cocok pakai `[Cara Singkat]` daripada `[Mulai cepat]`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +1. [Cara](/docs/recipes/): Temukan beberapa jawaban cepat untuk menyelesaikan beberapa tugas spesifik dan umum dengan Gatsby.
> ... Temukan beberapa jawaban cepat untuk menyelesaikan beberapa tugas spesifik dan umum dengan Gatsby.
`jawaban cepat` menjadi `jawaban singkat`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +2. Pilih petualangan Anda sendiri dan baca dengan teliti berbagai bagian pada dokumen Gatsby:
`petualangan` menjadi `cara`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +   - [Panduan Referensi](/docs/guides/): Pelajari tentang berbagai topik berbeda seputar membangun dengan Gatsby, seperti sumber data, *deployment*, dan banyak lagi.
`membangun` tambahkan `membangun web/aplikasi`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +   - [Panduan Konseptual](/docs/conceptual-guide/): Baca gambaran tingkat tinggi dari pendekatan Gatsby.
> Baca gambaran tingkat tinggi dari pendekatan Gatsby.
 
`Baca cara pendekatan atau konsep Gatsby secara garis besarnya.`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +3. Lihatlah perpustakaan [Ekosistem](/ecosystem/) untuk permulaan dan *plugins* Gatsby, serta sumber daya komunitas eksternal.
> ...serta sumber daya komunitas eksternal.

`serta baca juga bahan - bahan dari komunitas Gatsby diluar.`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +## Mulai berkontribusi
`berkontribusi` menjadi `kontribusi`

2019-10-29 23:15 UTC, cendekia commented on docs/docs/index.md
> +Kunjungi bagian [Berkontribusi](/contributing/) untuk menemukan panduan tentang komunitas Gatsby, kode etik, dan cara memulai berkontribusi ke Gatsby.
`[Berkontribusi]` menjadi `[Kontribusi]`

2019-10-29 23:37 UTC, cendekia commented
Thank you for contributing :purple_heart:.
There are some requested changes tho, but feel free to put an arguments if you have different though :)))

2019-10-30 02:09 UTC, bangunbagustapa commented on docs/docs/index.md
> +3. Lihatlah perpustakaan [Ekosistem](/ecosystem/) untuk permulaan dan *plugins* Gatsby, serta sumber daya komunitas eksternal.
You mean `bahan-bahan` without space, right?

2019-10-30 04:13 UTC, bangunbagustapa commented
Fixed the translation based on suggestions [#11423a6](https://github.com/gatsbyjs/gatsby-id/pull/4/commits/11423a60469cd543f9b3c9062fa16f60213dbead), thank you @cendekia.

2019-10-30 04:46 UTC, cendekia approved these changes
:rocket:

2019-10-30 04:46 UTC, merged