Translate docs/quick-start
gatsbyjs/gatsby-id pull request #6
Opened 2019-10-29 12:46 UTC by bangunbagustapa

Translated Quick Start page. Please review and give me some feedback for this translation.

2019-10-29 23:42 UTC, cendekia commented on docs/docs/quick-start.md
> +title: Mulai Cepat
`Mulai Cepat` menjadi `Cara Singkat`

2019-10-29 23:47 UTC, cendekia commented on docs/docs/quick-start.md
> +Mulai cepat ini dimaksudkan untuk para pengembang tingkat menengah hingga tingkat lanjut. Untuk pengantar Gatsby, [buka tutorial kami](/tutorial/)!
> Mulai cepat ini dimaksudkan untuk...

`Bagian ini dimaksudkan untuk...`

> Untuk pengantar Gatsby

`Jika Anda masih baru dengan Gatsby, ...

2019-10-29 23:54 UTC, cendekia requested changes
Ada sedikit revisi ya @bangunbagustapa

2019-10-30 01:36 UTC, bangunbagustapa commented on docs/docs/quick-start.md
> +title: Mulai Cepat
Done [#895fbc8](https://github.com/gatsbyjs/gatsby-id/pull/6/commits/895fbc8bb101661cbb6d0e3b689aa91e44638aee)

2019-10-30 01:38 UTC, bangunbagustapa commented on docs/docs/quick-start.md
> +Mulai cepat ini dimaksudkan untuk para pengembang tingkat menengah hingga tingkat lanjut. Untuk pengantar Gatsby, [buka tutorial kami](/tutorial/)!
Done [`#895fbc8`](https://github.com/gatsbyjs/gatsby-id/pull/6/commits/895fbc8bb101661cbb6d0e3b689aa91e44638aee)

2019-10-30 01:54 UTC, cendekia approved these changes

2019-10-30 01:55 UTC, merged