Menerjemahkan halaman tutorial index
gatsbyjs/gatsby-id pull request #7
Opened 2019-10-30 05:16 UTC by iamyuu

Ada beberapa kata yang tidak saya terjemahkan agar tetap sesuai.

2019-10-31 00:26 UTC, coroo commented on docs/tutorial/index.md
> +Selamat datang di Gatsby! Kami senang Anda ada di sini. Tujuan dari tutorial ini adalah untuk memandu Anda mengatur dan menyebarkan situs Gatsby Anda menggunakan templat pemula. Saat kita menjalani p
its better use: "Untuk memandu Anda dalam mengatur dan menyebarkan situ Gatsby pertama Anda"

2019-10-31 00:51 UTC, coroo requested changes
I added some comment, please fix those first. I have another comment, but hopefully you can read it first before I added another comment again. Please, after you translate it, make sure you read it one more time again. And if you think you can't read it, please correct it first before push it. Thank you.

2019-10-31 00:51 UTC, coroo commented on docs/tutorial/index.md
> +Selamat datang di Gatsby! Kami senang Anda ada di sini. Tujuan dari tutorial ini adalah untuk memandu Anda mengatur dan menyebarkan situs Gatsby Anda menggunakan templat pemula. Saat kita menjalani p
Also, please change
"Saat kita menjalani proses itu,"
with 
"Dalam menjalani proses tersebut,"

2019-10-31 00:51 UTC, coroo commented on docs/tutorial/index.md
> +> Tutorial lengkap ini dimaksudkan agar dapat diakses oleh orang-orang tanpa banyak pengalaman pengembangan web (belum!) — tidak perlu menjadi seorang ahli. Jika Anda lebih suka melompat langsung ke
Tutorial lengkap ini dimaksudkan agar dapat diakses oleh orang-orang yang belum memiliki banyak pengalaman dalam pengembangan web tidak perlu menjadi seorang ahli.

2019-10-31 00:51 UTC, coroo commented on docs/tutorial/index.md
> +4.  [Membangun tata letak bersarang di Gatsby](/tutorial/part-three/): Tata letak adalah bagian dari situs Anda yang digunakan kembali di beberapa halaman seperti header dan footer.
Its better to keep "nested layouts" with italic text. So the text will be : "Membangun _nested layouts_ di Gatsby"

2019-10-31 00:51 UTC, coroo commented on docs/tutorial/index.md
> +2.  [Mengenal blok bangunan Gatsby](/tutorial/part-one/): Memulai proyek baru, mengembangkan, dan menyebarkan situs.
Keep it "building blocks", (with italic text) so it should be "Mengenal _building blocks_ pada Gatsby"

2019-10-31 04:03 UTC, iamyuu commented
I fixed it on d858c8a, review please @coroo

2019-11-01 07:55 UTC, coroo approved these changes
Thank you @iamyuu 😄

2019-11-01 07:55 UTC, merged